puts "Henrique".object_id
puts "Henrique".object_id
puts "Henrique".object_id
puts "Henrique".object_id
puts "Henrique".object_id
puts "=========="
puts :Henrique.object_id
puts :Henrique.object_id
puts :Henrique.object_id
puts :Henrique.object_id
puts :Henrique.object_id
